name: vote_your_spirits
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  flutter_keyboard_visibility: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^1.2.0

flutter:
  uses-material-design: true
